name: heatchmap
dependencies:
  - pip
  - python=3.10
  - pip:
    - datasets==3.2.0
    - huggingface-hub==0.27.1
    - geopandas==1.0.1
    - matplotlib==3.10.0
    - numpy==2.2.1
    - numexpr==2.10.2 
    - osmnx==1.7.0
    - pandas==2.2.3
    - rasterio==1.4.3
    - git+https://github.com/Hitchwiki/scikit-learn.git@main
    - scipy==1.15.0
    - shapely==2.0.6
    - tqdm==4.67.1


